### ISSUE TITLE
Github now supports multiple assignees

### ISSUE THREAD

**Issue by AndrejMitrovic** [dlang-bots/mention-bot#9]
This might make it easier to "distribute" the workload among contributors / reviewers if dlangbot assigns multiple reviewers (or perhaps just doesn't always pick the same assignee?).

**Comment by wilzbach** [comment]
> Github now supports multiple assignees

By default mention-bot assigns multiple reviewers and we deliberately limited it to the first one according to the diff algorithm (#5), because we believe that if multiple persons are in charge of supervising the PR no one eventually feels responsible.

> or perhaps just doesn't always pick the same assignee?

The first reviewer in the sorted list is picked:

https://github.com/dlang-bots/mention-bot/blob/master/server.js#L357

Btw I just looked a bit deeper and the two pools are sorted:

```
  deletedOwners = getSortedOwners(deletedOwners);
  allOwners = getSortedOwners(allOwners);
```

but then only concatenated and not sorted again:

https://github.com/dlang-bots/mention-bot/blob/master/mention-bot.js#L435

but I doubt that's the cause of your issue?

**Comment by AndrejMitrovic** [comment]
Ah nevermind then, I didn't look at the existing issues. Thanks. :)
